### ISSUE TITLE
Broken Links fix.

### ISSUE THREAD

**Issue by antreac** [KnowWhereGraph/knowwheregraph-lite#3]
When adjusting the queries found here : https://github.com/KnowWhereGraph/knowwheregraph-lite/commit/6c542c485284da26de0b8c60a64c963a8c674145  to add to the queries documentation, some of them had broken links. 
Queries with these numbers : 7b
8c
10b
11b
12b
13b
I have left blank spaces for them .

**Comment by shirlysteph** [comment]
@antreac I have made the fixes to the queries that you have mentioned including 7b. The updated queries can be found in the query document here https://docs.google.com/document/d/1BV68cDKvi98xtoxemcHeDGfez6crF4lXskhHgkF_8aY/edit
Please let me know if there are any other issues.
